ALTER TABLE "Projects" ADD COLUMN IF NOT EXISTS "IsArchived" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Projects" ADD COLUMN IF NOT EXISTS "ArchivedAt" TIMESTAMP NULL;
ALTER TABLE "Projects" ADD COLUMN IF NOT EXISTS "UpdatedAt" TIMESTAMP NULL;

CREATE INDEX IF NOT EXISTS "IX_Projects_IsArchived" ON "Projects" ("IsArchived");